# Generated by Django 4.0.2 on 2023-12-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0003_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='7cefa7', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
